#!/usr/bin/env bash
clear

# Root Paths
project_root="$(pwd)"
project_file="${project_root}/project.file"
project_sources="${project_root}/sources"
project_resources="${project_root}/resources"
project_builds="${project_root}/builds"
project_dists="${project_root}/dists"

# Helper Functions
create() { mkdir --parents "${@}"; }
remove() { rm --recursive --force "${@}"; }
exists() { [[ -e "${1}" ]]; }
get_property() {
  local block_name="${1%%.*}"
  local key="${1##*.}:"
  local value=
  local inside_block=false

  while read -r line; do
    if [[ "${line}" =~ ^"$block_name"[[:space:]]\{ ]]; then
      inside_block=true
      continue
    fi
    if $inside_block && [[ "${line}" =~ ^\}$ ]]; then
      inside_block=false
    fi

    if $inside_block; then
      if [[ "${line}" =~ ^"$key" ]]; then
        value="${line#"${key}"}"
        while [[ "${value}" =~ ^[[:space:]] ]]; do
          value="${value#[[:space:]]}"
        done

        echo "${value}"
        break
      fi
    fi
  done <"${project_file}"
}
has_files() {
  local dir="${1}"
  local ext="*"

  if [[ -n "${2}" ]]; then
    if [[ "${2}" =~ ^\. ]]; then
      ext="${ext}${2}"
    else
      ext="${2}"
    fi
  fi

  declare -a files=()
  readarray -t files < <(find "${dir}" -type f -name "${ext}")

  ((${#files} > 0))
}

# Project Paths
declare -A project=(
  [name]="$(get_property "application.name")"
  [id]="$(get_property "application.id")"
  [entry]="$(get_property "application.entry")"
  [version_code]="$(get_property "version.code")"
  [version_name]="$(get_property "version.name")"
  [min_sdk]="$(get_property "sdk.min")"
  [target_sdk]="$(get_property "sdk.target")"
  [compile_sdk]="$(get_property "sdk.compile")"
  [keystore_path]="$(get_property "keystore.path")"
  [password_file]="$(get_property "keystore.passwordFile")"
)
declare -A sources=(
  [java]="${project_sources}/java"
  [gen]="${project_sources}/generated"
)
declare -A resources=(
  [manifest]="${project_resources}/AndroidManifest.xml"
  [res]="${project_resources}/res"
)
declare -A builds=(
  [base_apk]="${project_builds}/base.apk"
  [aligned_apk]="${project_builds}/aligned.apk"
  [res]="${project_builds}/res.zip"
  [classes]="${project_builds}/classes"
  [dex]="${project_builds}/dex"
)
declare -A dists=(
  [release_apk]="${project_dists}/release.apk"
)
declare -A misc=(
  [platform]="$ANDROID_HOME/platforms/android-${project[compile_sdk]}/android.jar"
)

# Building Functions
link() {
  declare -a extra_link_flags=()
  create "${project_builds}"

  if exists "${resources[res]}" && has_files "${resources[res]}"; then
    aapt2 compile -v \
      --dir "${resources[res]}" \
      -o "${builds[res]}"
    extra_link_flags+=("${builds[res]}")
  fi

  remove "${sources[gen]}"
  aapt2 link -v \
    -o "${builds[base_apk]}" \
    --manifest "${resources[manifest]}" \
    -I "${misc[platform]}" \
    --java "${sources[gen]}" \
    --version-code "${project[version_code]}" \
    --version-name "${project[version_name]}" \
    --replace-version \
    --min-sdk-version "${project[min_sdk]}" \
    --target-sdk-version "${project[target_sdk]}" \
    --rename-manifest-package "${project[id]}" \
    "${extra_link_flags[@]}"
}
compile() {
  remove "${builds[classes]}"

  javac -g -deprecation -Xlint \
    -d "${builds[classes]}" \
    --class-path "${misc[platform]}" \
    --release 17 \
    --source-path "${sources[java]}:${sources[gen]}" \
    "$(find "${sources[java]}" -name "${project[entry]}.java")"
}
dex() {
  declare -a class_files=()
  readarray -t class_files < <(find "${builds[classes]}" -name "*.class")

  remove "${builds[dex]}"
  create "${builds[dex]}"

  d8 \
    --lib "${misc[platform]}" \
    --output "${builds[dex]}" \
    "${class_files[@]}"
}
update() {
  find "${builds[dex]}" -name "*.dex" \
    -exec zip -j "${builds[base_apk]}" {} +
}
align() {
  zipalign -v -f -P 16 4 \
    "${builds[base_apk]}" "${builds[aligned_apk]}"
}
sign() {
  create "${project_dists}"

  apksigner sign -v \
    --in "${builds[aligned_apk]}" \
    --out "${dists[release_apk]}" \
    --v4-signing-enabled "false" \
    --ks "${project[keystore_path]}" \
    --ks-pass file:"${project[password_file]}"
}

# Build
build() (
  set -e

  link
  if exists "${sources[java]}" && has_files "${sources[java]}" "${project[entry]}.java"; then
    compile
    dex
    update
  fi
  align
  sign
)
build
